# Generated by Django 6.0.1 on 2026-01-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_test',
            field=models.CharField(max_length=200),
        ),
    ]
