"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nv@hxewzw@fj%7n8&p0h0v=5c249xt-p*2dhxq7qh#$0(#up2d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # 디버그 모드 설정. 다양한 변수들의 상태 확인 가능. 배포할 때는 False.

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [ # 3rd party application 사용 가능. pip로 설치한 앱 또는 본인이 만든 app 추가. 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls',  # polls app 등록
    'account',  # account app 등록
    'django_bootstrap5', # django app 등록
]

MIDDLEWARE = [  # request와 response 사이의 주요 기능 레이어. 인증이나 보안과 관련된 내용들.
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [  # django template 관련 설정, 실제 뷰 (html, 변수)
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = { # DB 엔진의 연결 설정
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # 연결할 DB 엔진 (Lib)
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


######################################
# 사용자 관리 시 사용하는 UserModel 변경
######################################
AUTH_USER_MODEL = "account.CustomUser"  

# http://127.0.0.1:8000/polls/vote_create -> login 페이지로 이동
# http://127.0.0.1:8000/account/login?next=/polls/vote_create
######################################
# 로그인 안 한 사용자가 @login_required View 함수를 호출했을 때 이동할 url
# -> 로그인 페이지로 이동 (/account/login?next=View의 URL)
######################################
LOGIN_URL = '/account/login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = 'static/'  # 정적 파일의 URL (css, javascript, image, etc)
